stages:
  - generate
  - run

generate-config:
  image: "gradle:7.6.4-jdk8"
  stage: generate
  script:
    - gradle -b gitlab-ci.gradle.kts generateGitlabCi
  artifacts:
    paths:
      - .gitlab-ci-generated.yml

child-pipeline:
  stage: run
  trigger:
    strategy: depend
    include:
      - artifact: .gitlab-ci-generated.yml
        job: generate-config