name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Create JReleaser Config
        env:
          JRELEASER_FILE: ${{ secrets.JRELEASER_FILE }}
        run: |
          mkdir -p ~/.jreleaser
          printf "%s" "$JRELEASER_FILE" > ~/.jreleaser/config.toml
      - name: Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jreleaserDeploy -Pversion=${{ github.event.release.tag_name }}